name: Web CI

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/shared/**"
      - ".github/workflows/ci-web.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/shared/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter web lint
      - run: pnpm --filter web build
        env:
          NEXT_PUBLIC_API_ENDPOINT: http://localhost:5000/api
          NEXT_PUBLIC_PUBLIC_BASE_URL: http://localhost:3000
